sudo: required
dist: trusty
language: python
python:
  - "2.7"

matrix:
  fast_finish: true

env:
  - TEST_RUN="pep8 ."
  - TEST_RUN="rst-lint *.rst"

install:
  - pip install -r tests/requirements.txt

script: "$TEST_RUN"

notifications:
  email: False
